build-env applied

diff --git a/bin/go b/bin/go
--- a/bin/go
+++ b/bin/go
@@ -1,46 +1,57 @@
 #!/bin/bash
+# This file is generated by BuildEnv. Avoid updating it manually.
+# Instead, contribute to BuildEnv and use 'be_update'
 #
 
-if [ "$BUILD_ENV_LOADED" != "true" ]
+MOD=go
+    
+# From BuildEnv bin/pre-wrapper.sh
+
+BUILD_SCRIPT_PATH=$(dirname $0)
+BUILD_SCRIPT_LIB_PATH=$(dirname $BUILD_SCRIPT_PATH)/lib
+
+if [[ ! -f $BUILD_SCRIPT_LIB_PATH/run-build-env.sh ]]
 then
-   echo "Please go to your project and load your build environment. 'source build-env.sh'"
-   exit 1
+    echo "Unable to load build-env.sh. '$BUILD_SCRIPT_LIB_PATH/run-build-env.sh' not found"
+    exit 1
 fi
 
-cd $BUILD_ENV_PROJECT
+source $BUILD_SCRIPT_LIB_PATH/run-build-env.sh
+# From BuildEnv:modules/go/bin/go.sh
 
-if [ "$http_proxy" != "" ]
-then
-   PROXY="-e http_proxy=$http_proxy -e https_proxy=$http_proxy -e no_proxy=$no_proxy"
-fi
-
-USER="-u $(id -u)"
-
-if [ "$GOPATH" = "" ]
-then
-   echo "GOPATH not set. Please set it."
-   exit 1
-fi
-
-if [ "$CGO_ENABLED" = "0" ]
+if [[ "$CGO_ENABLED" = "0" ]]
 then
    GOBIN="/usr/local/go/bin/go-static"
 else
    GOBIN="/usr/local/go/bin/go"
 fi
 
-MOUNT="-v $GOPATH:/go -w /go/src/$BUILD_ENV_PROJECT_REL"
-
-if [ "$1" = "build" ] || [ "$1" = "install" ]
+if [[ "$1" = "build" ]] || [[ "$1" = "install" ]]
 then
    BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    BUILD_COMMIT=$(git log --format="%H" -1)
-   BUILD_DATE="$(git log --format="%ai" -1)"
-   BUILD_FLAGS="$1 -ldflags '-X main.build_branch=$BUILD_BRANCH -X main.build_commit=$BUILD_COMMIT'"
+   BUILD_DATE="$(git log --format="%ai" -1 | sed 's/ /_/g')"
+   GIT_TAG="$(git tag -l --points-at HEAD | grep -v latest)"
+
+   BUILD_TAG=false
+   if [[ "$GIT_TAG" != "" ]]
+   then
+      if [[ -f version.go ]]
+      then
+         if [[ "$(grep $GIT_TAG version.go)" != "" ]]
+         then
+            BUILD_TAG=true
+         fi
+      else
+         BUILD_TAG=true
+      fi
+   fi
+   if [[ $BUILD_TAG = true ]]
+   then
+      echo "##### Building official $GIT_TAG #####"
+   fi
+   BUILD_FLAGS="$1 -ldflags '-X main.build_branch=$BUILD_BRANCH -X main.build_commit=$BUILD_COMMIT -X main.build_date=$BUILD_DATE -X main.build_tag=$BUILD_TAG'"
    shift
 fi
 
-echo "Running $BUILD_ENV_CONTAINER container in $BUILD_ENV_PROJECT_REL"
-
-eval $BUILD_ENV_DOCKER run --rm -it $MOUNT $PROXY $USER $BUILD_ENV_CONTAINER $GOBIN $BUILD_FLAGS "$@"
-
+docker_run $BE_PROJECT-go-env $GOBIN $BUILD_FLAGS "$@"
diff --git a/bin/inenv b/bin/inenv
--- a/bin/inenv
+++ b/bin/inenv
@@ -1,22 +1,53 @@
 #!/bin/bash
+# This file is generated by BuildEnv. Avoid updating it manually.
+# Instead, contribute to BuildEnv and use 'be_update'
 #
 
-if [ "$http_proxy" != "" ]
+MOD=core
+    
+# From BuildEnv bin/pre-wrapper.sh
+
+BUILD_SCRIPT_PATH=$(dirname $0)
+BUILD_SCRIPT_LIB_PATH=$(dirname $BUILD_SCRIPT_PATH)/lib
+
+if [[ ! -f $BUILD_SCRIPT_LIB_PATH/run-build-env.sh ]]
 then
-   PROXY="-e http_proxy=$http_proxy -e https_proxy=$http_proxy -e no_proxy=$no_proxy"
+    echo "Unable to load build-env.sh. '$BUILD_SCRIPT_LIB_PATH/run-build-env.sh' not found"
+    exit 1
 fi
 
-USER="-u $(id -u)"
-if [ "$GOPATH" = "" ]
+source $BUILD_SCRIPT_LIB_PATH/run-build-env.sh
+# Added from ../build-env/bin/inenv
+# From BuildEnv bin/inenv.sh
+
+if [[ "$1" == --help ]]
 then
-   echo "GOPATH not set. Please set it."
-   exit 1
+    echo "usage is inenv [module]
+
+inenv is used to enter in the builder module container with bash to get build context."
+    exit
 fi
 
-MOUNT="-v $GOPATH:/go -w /go/src/$BUILD_ENV_PROJECT_REL"
+if [[ -f $BUILD_ENV_PROJECT/build-env.modules ]]
+then
+    MODS=(`cat $BUILD_ENV_PROJECT/build-env.modules`)
 
-echo "Running $BUILD_ENV_CONTAINER container in $BUILD_ENV_PROJECT_REL"
+    case ${#MODS[@]} in
+    0) IMAGE=alpine ;;
+    1) IMAGE="${BE_PROJECT}-${MODS[0]}-env" ; MOD=${MODS[0]};;
+    *)
+        for MOD in ${MODS[@]}
+        do
+            if [[ $MOD = $1 ]]
+            then
+                IMAGE="${BE_PROJECT}-$1-env"
+                break
+            fi
+        done
+        ;;
+    esac
+else
+    IMAGE=alpine
+fi
 
-$BUILD_ENV_DOCKER run --rm -it $MOUNT $PROXY $USER $BUILD_ENV_CONTAINER bash
-
-
+docker_run $IMAGE bash
